// ============================================================
// MOCK DATA — Simulates Supabase PostgreSQL backend
// All data is strictly typed. Replace with Supabase client calls
// when the DB is wired up.
// ============================================================

import type {
  Task,
  InventoryItem,
  DailyLog,
  WorkoutEntry,
  MacroLog,
} from "./types";
import { localDateString } from "./utils";

// ─── HELPER ──────────────────────────────────────────────────
function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return localDateString(d);
}

// ─── TASKS ───────────────────────────────────────────────────
export const MOCK_TASKS: Task[] = [
  // ── P0 · CERTIFICAZIONE INGLESE & DATA SCIENCE ──
  {
    id: "t-001",
    title: "IELTS Mock Test completo — 4 sezioni",
    category: "Study",
    area: "IELTS",
    priority: "P0",
    bucket: "Today",
    energy_required: 5,
    status: "InProgress",
    duration_mins: 90,
    created_at: daysAgo(0),
    energy_block: "Peak",
    notes: "P0 — Simulazione esame. Obiettivo B2 passivo → C1 attivo",
  },
  {
    id: "t-002",
    title: "Math for DS — Algebra Lineare & Calcolo",
    category: "Study",
    area: "DSE",
    priority: "P0",
    bucket: "Today",
    energy_required: 5,
    status: "Todo",
    duration_mins: 90,
    created_at: daysAgo(0),
    energy_block: "Peak",
    notes: "P0 — Deep Work 10:30-12:00. Prerequisito Polito DS&E",
  },
  {
    id: "t-003",
    title: "IELTS Writing Task 2 — pratica essays",
    category: "Study",
    area: "IELTS",
    priority: "P0",
    bucket: "ThisWeek",
    energy_required: 4,
    status: "Todo",
    duration_mins: 60,
    created_at: daysAgo(1),
    energy_block: "Peak",
    notes: "P0 — Certificazione Cambridge / IELTS",
  },
  {
    id: "t-004",
    title: "Statistics for DS — probabilità e distribuzioni",
    category: "Study",
    area: "DSE",
    priority: "P0",
    bucket: "ThisWeek",
    energy_required: 4,
    status: "Todo",
    duration_mins: 90,
    created_at: daysAgo(1),
    energy_block: "Peak",
    notes: "P0 — Basi Data Science per ammissione Master",
  },

  // ── P1 · OUTREACH AGENT ──
  {
    id: "t-005",
    title: "Invio 50 email outreach — batch giornaliero",
    category: "Work",
    area: "Projects",
    priority: "P1",
    bucket: "Today",
    energy_required: 3,
    status: "InProgress",
    duration_mins: 90,
    created_at: daysAgo(0),
    energy_block: "Trough",
    notes: "P1 — Target N=500 prima del pivot sul copy. Slot 12:00-13:30",
  },
  {
    id: "t-006",
    title: "Monitoraggio pipeline CRM e risposte",
    category: "Work",
    area: "Projects",
    priority: "P1",
    bucket: "Today",
    energy_required: 2,
    status: "Todo",
    duration_mins: 45,
    created_at: daysAgo(0),
    energy_block: "Trough",
    notes: "P1 — Validazione outreach: analisi open rate e reply rate",
  },
  {
    id: "t-007",
    title: "Feedback cold callers + aggiornamento script",
    category: "Work",
    area: "Projects",
    priority: "P1",
    bucket: "ThisWeek",
    energy_required: 3,
    status: "Todo",
    duration_mins: 90,
    created_at: daysAgo(1),
    energy_block: "Rebound",
    notes: "P1 — Slot manutenzione 15:30-17:30",
  },
  {
    id: "t-008",
    title: "Setup scraping agent per lead generation",
    category: "Work",
    area: "Projects",
    priority: "P1",
    bucket: "ThisWeek",
    energy_required: 4,
    status: "Todo",
    duration_mins: 120,
    created_at: daysAgo(2),
    energy_block: "Peak",
    notes: "P1 — AI writing + automation pipeline outreach",
  },

  // ── P2 · HEALTH / BIO ──
  {
    id: "t-009",
    title: "Protocollo Huberman — luce solare mattina",
    category: "Admin",
    area: "Admin",
    priority: "P2",
    bucket: "Today",
    energy_required: 1,
    status: "Todo",
    duration_mins: 30,
    created_at: daysAgo(0),
    energy_block: "Peak",
    notes: "P2 — 10:00-10:30, no schermi, reset circadiano",
  },
  {
    id: "t-010",
    title: "NSDR / Micro-nap pomeriggio",
    category: "Admin",
    area: "Admin",
    priority: "P2",
    bucket: "Today",
    energy_required: 1,
    status: "Todo",
    duration_mins: 45,
    created_at: daysAgo(0),
    energy_block: "Trough",
    notes: "P2 — 14:45-15:30, recupero glinfatico",
  },

  // ── P3 · SIDE HUSTLE (solo weekend o post-KPI P0/P1) ──
  {
    id: "t-011",
    title: "Skappa — sviluppo feature",
    category: "Work",
    area: "Websites",
    priority: "P3",
    bucket: "Backlog",
    energy_required: 3,
    status: "Inbox",
    duration_mins: 120,
    created_at: daysAgo(3),
    notes: "P3 — Kill-switch feriali attivo. Solo weekend o post-KPI P0/P1",
  },
  {
    id: "t-012",
    title: "Modelle IA — creazione contenuto",
    category: "Work",
    area: "Projects",
    priority: "P3",
    bucket: "Backlog",
    energy_required: 3,
    status: "Inbox",
    duration_mins: 120,
    created_at: daysAgo(3),
    notes: "P3 — Kill-switch feriali attivo. Solo weekend o post-KPI P0/P1",
  },
];

// ─── INVENTORY ───────────────────────────────────────────────
export const MOCK_INVENTORY: InventoryItem[] = [
  // ── Integratori ──
  {
    id: "inv-001",
    name: "Omega 3",
    category: "Supplement",
    current_stock: 90,
    threshold: 30,
    auto_reorder: true,
    unit: "cps",
    daily_usage: 3,
  },
  {
    id: "inv-002",
    name: "Multivitaminico",
    category: "Supplement",
    current_stock: 30,
    threshold: 10,
    auto_reorder: true,
    unit: "cps",
    daily_usage: 1,
  },
  {
    id: "inv-003",
    name: "Creatina Monoidrato",
    category: "Supplement",
    current_stock: 150,
    threshold: 50,
    auto_reorder: true,
    unit: "g",
    daily_usage: 5,
  },

  // ── Proteine ──
  {
    id: "inv-004",
    name: "Whey Proteine Isolate",
    category: "Food",
    current_stock: 500,
    threshold: 150,
    auto_reorder: true,
    unit: "g",
    daily_usage: 75,
  },
  {
    id: "inv-005",
    name: "Petto di Pollo",
    category: "Food",
    current_stock: 450,
    threshold: 300,
    auto_reorder: false,
    unit: "g",
    daily_usage: 150,
  },
  {
    id: "inv-006",
    name: "Albume Liquido",
    category: "Food",
    current_stock: 1000,
    threshold: 400,
    auto_reorder: false,
    unit: "ml",
    daily_usage: 450,
  },
  {
    id: "inv-007",
    name: "Uova",
    category: "Food",
    current_stock: 10,
    threshold: 6,
    auto_reorder: false,
    unit: "uova",
    daily_usage: 2,
  },
  {
    id: "inv-008",
    name: "Yogurt Greco",
    category: "Food",
    current_stock: 400,
    threshold: 200,
    auto_reorder: false,
    unit: "g",
    daily_usage: 200,
  },
  {
    id: "inv-009",
    name: "Fesa di Tacchino",
    category: "Food",
    current_stock: 240,
    threshold: 120,
    auto_reorder: false,
    unit: "g",
    daily_usage: 120,
  },
  {
    id: "inv-010",
    name: "Tonno al Naturale",
    category: "Food",
    current_stock: 480,
    threshold: 120,
    auto_reorder: false,
    unit: "g",
    daily_usage: 120,
  },
  {
    id: "inv-011",
    name: "Pesce Bianco (surgelato)",
    category: "Food",
    current_stock: 500,
    threshold: 250,
    auto_reorder: false,
    unit: "g",
    daily_usage: 250,
  },
  {
    id: "inv-012",
    name: "Kefir",
    category: "Food",
    current_stock: 300,
    threshold: 150,
    auto_reorder: false,
    unit: "g",
    daily_usage: 150,
  },

  // ── Carboidrati ──
  {
    id: "inv-013",
    name: "Riso Basmati",
    category: "Food",
    current_stock: 1000,
    threshold: 320,
    auto_reorder: false,
    unit: "g",
    daily_usage: 80,
  },
  {
    id: "inv-014",
    name: "Pasta Integrale",
    category: "Food",
    current_stock: 800,
    threshold: 300,
    auto_reorder: false,
    unit: "g",
    daily_usage: 80,
  },
  {
    id: "inv-015",
    name: "Patate",
    category: "Food",
    current_stock: 1500,
    threshold: 700,
    auto_reorder: false,
    unit: "g",
    daily_usage: 350,
  },
  {
    id: "inv-016",
    name: "Gallette di Riso/Mais",
    category: "Food",
    current_stock: 300,
    threshold: 120,
    auto_reorder: false,
    unit: "g",
    daily_usage: 60,
  },
  {
    id: "inv-017",
    name: "Pan Bauletto Integrale",
    category: "Food",
    current_stock: 350,
    threshold: 100,
    auto_reorder: false,
    unit: "g",
    daily_usage: 50,
  },
  {
    id: "inv-018",
    name: "Farina d'Avena Aromatizzata",
    category: "Food",
    current_stock: 300,
    threshold: 90,
    auto_reorder: false,
    unit: "g",
    daily_usage: 30,
  },
  {
    id: "inv-019",
    name: "Cous Cous Integrale",
    category: "Food",
    current_stock: 500,
    threshold: 210,
    auto_reorder: false,
    unit: "g",
    daily_usage: 70,
  },

  // ── Verdure & Condimenti ──
  {
    id: "inv-020",
    name: "Verdure Miste",
    category: "Food",
    current_stock: 800,
    threshold: 400,
    auto_reorder: false,
    unit: "g",
    daily_usage: 400,
  },
  {
    id: "inv-021",
    name: "Olio EVO",
    category: "Food",
    current_stock: 250,
    threshold: 60,
    auto_reorder: false,
    unit: "ml",
    daily_usage: 20,
  },
  {
    id: "inv-022",
    name: "Frutta Secca (senza sale)",
    category: "Food",
    current_stock: 200,
    threshold: 70,
    auto_reorder: false,
    unit: "g",
    daily_usage: 35,
  },
];

// ─── DAILY LOGS (last 14 days) ────────────────────────────────
export const MOCK_DAILY_LOGS: DailyLog[] = [
  {
    date: daysAgo(13),
    sleep_hours: 6.5,
    rhr: 58,
    training_rpe: 7,
    pomodoros_completed: 4,
    tasks_completed: 3,
    macros_hit: false,
    hrv: 52,
    water_ml: 2200,
    mood: 3,
  },
  {
    date: daysAgo(12),
    sleep_hours: 7.5,
    rhr: 55,
    training_rpe: 0,
    pomodoros_completed: 8,
    tasks_completed: 6,
    macros_hit: true,
    hrv: 68,
    water_ml: 2800,
    mood: 4,
  },
  {
    date: daysAgo(11),
    sleep_hours: 8.0,
    rhr: 54,
    training_rpe: 8,
    pomodoros_completed: 6,
    tasks_completed: 5,
    macros_hit: true,
    hrv: 72,
    water_ml: 3000,
    mood: 5,
  },
  {
    date: daysAgo(10),
    sleep_hours: 7.0,
    rhr: 57,
    training_rpe: 6,
    pomodoros_completed: 5,
    tasks_completed: 4,
    macros_hit: true,
    hrv: 61,
    water_ml: 2500,
    mood: 4,
  },
  {
    date: daysAgo(9),
    sleep_hours: 6.0,
    rhr: 62,
    training_rpe: 0,
    pomodoros_completed: 3,
    tasks_completed: 2,
    macros_hit: false,
    hrv: 48,
    water_ml: 1800,
    mood: 2,
  },
  {
    date: daysAgo(8),
    sleep_hours: 9.0,
    rhr: 53,
    training_rpe: 7,
    pomodoros_completed: 7,
    tasks_completed: 6,
    macros_hit: true,
    hrv: 75,
    water_ml: 3200,
    mood: 5,
  },
  {
    date: daysAgo(7),
    sleep_hours: 7.5,
    rhr: 55,
    training_rpe: 9,
    pomodoros_completed: 4,
    tasks_completed: 3,
    macros_hit: true,
    hrv: 63,
    water_ml: 2600,
    mood: 4,
  },
  // Last 7 days (used in charts)
  {
    date: daysAgo(6),
    sleep_hours: 7.0,
    rhr: 56,
    training_rpe: 5,
    pomodoros_completed: 6,
    tasks_completed: 5,
    macros_hit: true,
    hrv: 66,
    water_ml: 2700,
    mood: 4,
  },
  {
    date: daysAgo(5),
    sleep_hours: 6.5,
    rhr: 59,
    training_rpe: 0,
    pomodoros_completed: 5,
    tasks_completed: 4,
    macros_hit: false,
    hrv: 58,
    water_ml: 2300,
    mood: 3,
  },
  {
    date: daysAgo(4),
    sleep_hours: 8.0,
    rhr: 54,
    training_rpe: 8,
    pomodoros_completed: 8,
    tasks_completed: 7,
    macros_hit: true,
    hrv: 74,
    water_ml: 3100,
    mood: 5,
  },
  {
    date: daysAgo(3),
    sleep_hours: 7.5,
    rhr: 55,
    training_rpe: 7,
    pomodoros_completed: 7,
    tasks_completed: 5,
    macros_hit: true,
    hrv: 70,
    water_ml: 2900,
    mood: 4,
  },
  {
    date: daysAgo(2),
    sleep_hours: 7.0,
    rhr: 57,
    training_rpe: 0,
    pomodoros_completed: 6,
    tasks_completed: 4,
    macros_hit: true,
    hrv: 65,
    water_ml: 2600,
    mood: 4,
  },
  {
    date: daysAgo(1),
    sleep_hours: 8.5,
    rhr: 52,
    training_rpe: 9,
    pomodoros_completed: 5,
    tasks_completed: 4,
    macros_hit: true,
    hrv: 71,
    water_ml: 3000,
    mood: 5,
  },
  {
    date: daysAgo(0),
    sleep_hours: 7.5,
    rhr: 55,
    training_rpe: 6,
    pomodoros_completed: 3,
    tasks_completed: 2,
    macros_hit: false,
    hrv: 60,
    water_ml: 1500,
    mood: 3,
  },
];

// ─── WORKOUT ENTRIES — Scheda reale ─────────────────────────
// Lunedì: Petto / Gambe / Spalle
// Mercoledì: Schiena / Bicipiti / Posteriori coscia
// Venerdì: Spalle / Tricipiti / Core / Gambe
// Mar/Gio/Sab/Dom: riposo
export const MOCK_WORKOUT_ENTRIES: WorkoutEntry[] = [

  // ═══ LUNEDÌ — settimana precedente (daysAgo(11)) ════════════
  {
    id: "w-001",
    date: daysAgo(11),
    exercise: "Spinte Manubri Panca 45°",
    muscle_group: "Petto",
    weight: 20,
    weight_unit: "kg",
    reps: 10,
    sets: 3,
    progressive_overload_achieved: false,
    notes: "Manubri per lato",
  },
  {
    id: "w-002",
    date: daysAgo(11),
    exercise: "Chest Press",
    muscle_group: "Petto",
    weight: 60,
    weight_unit: "kg",
    reps: 12,
    sets: 3,
    progressive_overload_achieved: false,
  },
  {
    id: "w-003",
    date: daysAgo(11),
    exercise: "Leg Press",
    muscle_group: "Gambe",
    weight: 120,
    weight_unit: "kg",
    reps: 10,
    sets: 4,
    progressive_overload_achieved: false,
  },
  {
    id: "w-004",
    date: daysAgo(11),
    exercise: "Alzate Laterali Manubri",
    muscle_group: "Spalle",
    weight: 10,
    weight_unit: "kg",
    reps: 12,
    sets: 3,
    progressive_overload_achieved: false,
    notes: "Manubri per lato",
  },

  // ═══ LUNEDÌ — settimana corrente (daysAgo(4)) ═══════════════
  {
    id: "w-005",
    date: daysAgo(4),
    exercise: "Spinte Manubri Panca 45°",
    muscle_group: "Petto",
    weight: 22,
    weight_unit: "kg",
    reps: 10,
    sets: 3,
    progressive_overload_achieved: true,
    notes: "Manubri per lato",
  },
  {
    id: "w-006",
    date: daysAgo(4),
    exercise: "Chest Press",
    muscle_group: "Petto",
    weight: 62.5,
    weight_unit: "kg",
    reps: 12,
    sets: 3,
    progressive_overload_achieved: true,
  },
  {
    id: "w-007",
    date: daysAgo(4),
    exercise: "Leg Press",
    muscle_group: "Gambe",
    weight: 125,
    weight_unit: "kg",
    reps: 10,
    sets: 4,
    progressive_overload_achieved: true,
  },
  {
    id: "w-008",
    date: daysAgo(4),
    exercise: "Alzate Laterali Manubri",
    muscle_group: "Spalle",
    weight: 10,
    weight_unit: "kg",
    reps: 13,
    sets: 3,
    progressive_overload_achieved: true,
    notes: "Manubri per lato",
  },

  // ═══ MERCOLEDÌ — settimana precedente (daysAgo(9)) ══════════
  {
    id: "w-009",
    date: daysAgo(9),
    exercise: "Stacco Rumeno Manubri",
    muscle_group: "Posteriori Coscia",
    weight: 28,
    weight_unit: "kg",
    reps: 10,
    sets: 3,
    progressive_overload_achieved: false,
    notes: "Manubri per lato",
  },
  {
    id: "w-010",
    date: daysAgo(9),
    exercise: "Lat Machine Presa Media",
    muscle_group: "Schiena",
    weight: 62.5,
    weight_unit: "kg",
    reps: 12,
    sets: 3,
    progressive_overload_achieved: false,
  },
  {
    id: "w-011",
    date: daysAgo(9),
    exercise: "Curl Bilanciere EZ",
    muscle_group: "Bicipiti",
    weight: 32,
    weight_unit: "kg",
    reps: 10,
    sets: 3,
    progressive_overload_achieved: false,
  },

  // ═══ MERCOLEDÌ — settimana corrente (daysAgo(2)) ════════════
  {
    id: "w-012",
    date: daysAgo(2),
    exercise: "Stacco Rumeno Manubri",
    muscle_group: "Posteriori Coscia",
    weight: 30,
    weight_unit: "kg",
    reps: 10,
    sets: 3,
    progressive_overload_achieved: true,
    notes: "Manubri per lato",
  },
  {
    id: "w-013",
    date: daysAgo(2),
    exercise: "Lat Machine Presa Media",
    muscle_group: "Schiena",
    weight: 65,
    weight_unit: "kg",
    reps: 12,
    sets: 3,
    progressive_overload_achieved: true,
  },
  {
    id: "w-014",
    date: daysAgo(2),
    exercise: "Curl Bilanciere EZ",
    muscle_group: "Bicipiti",
    weight: 34,
    weight_unit: "kg",
    reps: 10,
    sets: 3,
    progressive_overload_achieved: true,
  },

  // ═══ VENERDÌ — settimana precedente (daysAgo(7)) ════════════
  {
    id: "w-015",
    date: daysAgo(7),
    exercise: "Shoulder Press",
    muscle_group: "Spalle",
    weight: 50,
    weight_unit: "kg",
    reps: 12,
    sets: 3,
    progressive_overload_achieved: false,
  },
  {
    id: "w-016",
    date: daysAgo(7),
    exercise: "Push Down Corda",
    muscle_group: "Tricipiti",
    weight: 22,
    weight_unit: "kg",
    reps: 15,
    sets: 3,
    progressive_overload_achieved: false,
  },
  {
    id: "w-017",
    date: daysAgo(7),
    exercise: "French Press Manubri",
    muscle_group: "Tricipiti",
    weight: 14,
    weight_unit: "kg",
    reps: 12,
    sets: 3,
    progressive_overload_achieved: false,
    notes: "Manubri per lato",
  },

  // ═══ VENERDÌ — settimana corrente (daysAgo(0)) ══════════════
  {
    id: "w-018",
    date: daysAgo(0),
    exercise: "Shoulder Press",
    muscle_group: "Spalle",
    weight: 52.5,
    weight_unit: "kg",
    reps: 12,
    sets: 3,
    progressive_overload_achieved: true,
  },
  {
    id: "w-019",
    date: daysAgo(0),
    exercise: "Push Down Corda",
    muscle_group: "Tricipiti",
    weight: 24,
    weight_unit: "kg",
    reps: 15,
    sets: 3,
    progressive_overload_achieved: true,
  },
  {
    id: "w-020",
    date: daysAgo(0),
    exercise: "French Press Manubri",
    muscle_group: "Tricipiti",
    weight: 16,
    weight_unit: "kg",
    reps: 12,
    sets: 3,
    progressive_overload_achieved: true,
    notes: "Manubri per lato",
  },
];

// ─── MACRO LOGS (last 7 days) ─────────────────────────────────
export const MOCK_MACRO_LOGS: MacroLog[] = [
  {
    date: daysAgo(6),
    calories_target: 2800,
    calories_actual: 2750,
    protein_g_target: 180,
    protein_g_actual: 175,
    carbs_g_target: 300,
    carbs_g_actual: 290,
    fat_g_target: 80,
    fat_g_actual: 78,
  },
  {
    date: daysAgo(5),
    calories_target: 2800,
    calories_actual: 2200,
    protein_g_target: 180,
    protein_g_actual: 140,
    carbs_g_target: 300,
    carbs_g_actual: 240,
    fat_g_target: 80,
    fat_g_actual: 60,
  },
  {
    date: daysAgo(4),
    calories_target: 2800,
    calories_actual: 2850,
    protein_g_target: 180,
    protein_g_actual: 185,
    carbs_g_target: 300,
    carbs_g_actual: 305,
    fat_g_target: 80,
    fat_g_actual: 82,
  },
  {
    date: daysAgo(3),
    calories_target: 2800,
    calories_actual: 2780,
    protein_g_target: 180,
    protein_g_actual: 178,
    carbs_g_target: 300,
    carbs_g_actual: 295,
    fat_g_target: 80,
    fat_g_actual: 79,
  },
  {
    date: daysAgo(2),
    calories_target: 2800,
    calories_actual: 2760,
    protein_g_target: 180,
    protein_g_actual: 172,
    carbs_g_target: 300,
    carbs_g_actual: 298,
    fat_g_target: 80,
    fat_g_actual: 77,
  },
  {
    date: daysAgo(1),
    calories_target: 2800,
    calories_actual: 2900,
    protein_g_target: 180,
    protein_g_actual: 190,
    carbs_g_target: 300,
    carbs_g_actual: 310,
    fat_g_target: 80,
    fat_g_actual: 85,
  },
  {
    date: daysAgo(0),
    calories_target: 2800,
    calories_actual: 1600,
    protein_g_target: 180,
    protein_g_actual: 95,
    carbs_g_target: 300,
    carbs_g_actual: 180,
    fat_g_target: 80,
    fat_g_actual: 55,
  },
];
