// ============================================================
// MOCK DATA — Simulates Supabase PostgreSQL backend
// All data is strictly typed. Replace with Supabase client calls
// when the DB is wired up.
// ============================================================

import type {
  Task,
  InventoryItem,
  DailyLog,
  WorkoutEntry,
  MacroLog,
} from "./types";

// ─── HELPER ──────────────────────────────────────────────────
function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString().split("T")[0];
}

// ─── TASKS ───────────────────────────────────────────────────
export const MOCK_TASKS: Task[] = [
  // ── INBOX (raw captures) ──
  {
    id: "t-001",
    title: "Research best sleep tracking apps",
    category: "Study",
    energy_required: 2,
    status: "Inbox",
    duration_mins: 30,
    created_at: daysAgo(0),
  },
  {
    id: "t-002",
    title: "Reply to client invoice email",
    category: "Admin",
    energy_required: 1,
    status: "Inbox",
    duration_mins: 15,
    created_at: daysAgo(0),
  },
  {
    id: "t-003",
    title: "Draft Q2 strategy doc",
    category: "Work",
    energy_required: 5,
    status: "Inbox",
    duration_mins: 90,
    created_at: daysAgo(1),
  },

  // ── TODO ──
  {
    id: "t-004",
    title: "Complete English grammar chapter 7",
    category: "Study",
    energy_required: 3,
    status: "Todo",
    duration_mins: 45,
    created_at: daysAgo(2),
    energy_block: "Peak",
  },
  {
    id: "t-005",
    title: "Redesign landing page hero section",
    category: "Work",
    energy_required: 4,
    status: "Todo",
    duration_mins: 120,
    created_at: daysAgo(2),
    energy_block: "Peak",
  },
  {
    id: "t-006",
    title: "Update tax documents",
    category: "Admin",
    energy_required: 2,
    status: "Todo",
    duration_mins: 30,
    created_at: daysAgo(3),
    energy_block: "Trough",
  },
  {
    id: "t-007",
    title: "Read: Atomic Habits chapter 4",
    category: "Study",
    energy_required: 2,
    status: "Todo",
    duration_mins: 40,
    created_at: daysAgo(1),
    energy_block: "Rebound",
  },

  // ── IN PROGRESS ──
  {
    id: "t-008",
    title: "Build dashboard data layer",
    category: "Work",
    energy_required: 5,
    status: "InProgress",
    duration_mins: 180,
    created_at: daysAgo(1),
    energy_block: "Peak",
    notes: "Mock data done, wiring UI components next",
  },
  {
    id: "t-009",
    title: "Spanish conversation practice",
    category: "Study",
    energy_required: 3,
    status: "InProgress",
    duration_mins: 30,
    created_at: daysAgo(2),
    energy_block: "Rebound",
  },

  // ── DONE ──
  {
    id: "t-010",
    title: "Weekly meal prep",
    category: "Admin",
    energy_required: 2,
    status: "Done",
    duration_mins: 90,
    created_at: daysAgo(4),
  },
  {
    id: "t-011",
    title: "Client call — project kickoff",
    category: "Work",
    energy_required: 3,
    status: "Done",
    duration_mins: 60,
    created_at: daysAgo(3),
  },
  {
    id: "t-012",
    title: "Morning journaling session",
    category: "Study",
    energy_required: 1,
    status: "Done",
    duration_mins: 20,
    created_at: daysAgo(5),
  },
];

// ─── INVENTORY ───────────────────────────────────────────────
export const MOCK_INVENTORY: InventoryItem[] = [
  // ── Supplements ──
  {
    id: "inv-001",
    name: "Creatine Monohydrate",
    category: "Supplement",
    current_stock: 45,
    threshold: 30,
    auto_reorder: true,
    unit: "g",
    daily_usage: 5,
  },
  {
    id: "inv-002",
    name: "Vitamin D3 (5000 IU)",
    category: "Supplement",
    current_stock: 12,
    threshold: 20,
    auto_reorder: true,
    unit: "pills",
    daily_usage: 1,
  },
  {
    id: "inv-003",
    name: "Magnesium Glycinate",
    category: "Supplement",
    current_stock: 8,
    threshold: 15,
    auto_reorder: true,
    unit: "pills",
    daily_usage: 2,
  },
  {
    id: "inv-004",
    name: "Omega-3 Fish Oil",
    category: "Supplement",
    current_stock: 60,
    threshold: 20,
    auto_reorder: false,
    unit: "pills",
    daily_usage: 3,
  },
  {
    id: "inv-005",
    name: "Zinc",
    category: "Supplement",
    current_stock: 25,
    threshold: 10,
    auto_reorder: false,
    unit: "pills",
    daily_usage: 1,
  },
  {
    id: "inv-006",
    name: "Ashwagandha KSM-66",
    category: "Supplement",
    current_stock: 5,
    threshold: 10,
    auto_reorder: true,
    unit: "pills",
    daily_usage: 2,
  },

  // ── Food staples ──
  {
    id: "inv-007",
    name: "Chicken Breast",
    category: "Food",
    current_stock: 400,
    threshold: 500,
    auto_reorder: false,
    unit: "g",
    daily_usage: 200,
  },
  {
    id: "inv-008",
    name: "Oats",
    category: "Food",
    current_stock: 800,
    threshold: 400,
    auto_reorder: false,
    unit: "g",
    daily_usage: 80,
  },
  {
    id: "inv-009",
    name: "Eggs",
    category: "Food",
    current_stock: 4,
    threshold: 6,
    auto_reorder: false,
    unit: "units",
    daily_usage: 3,
  },
  {
    id: "inv-010",
    name: "Greek Yogurt",
    category: "Food",
    current_stock: 200,
    threshold: 500,
    auto_reorder: false,
    unit: "g",
    daily_usage: 200,
  },
  {
    id: "inv-011",
    name: "Whey Protein",
    category: "Food",
    current_stock: 600,
    threshold: 300,
    auto_reorder: true,
    unit: "g",
    daily_usage: 60,
  },
  {
    id: "inv-012",
    name: "Rice",
    category: "Food",
    current_stock: 1500,
    threshold: 500,
    auto_reorder: false,
    unit: "g",
    daily_usage: 150,
  },
];

// ─── DAILY LOGS (last 14 days) ────────────────────────────────
export const MOCK_DAILY_LOGS: DailyLog[] = [
  {
    date: daysAgo(13),
    sleep_hours: 6.5,
    rhr: 58,
    training_rpe: 7,
    pomodoros_completed: 4,
    tasks_completed: 3,
    macros_hit: false,
    hrv: 52,
    water_ml: 2200,
    mood: 3,
  },
  {
    date: daysAgo(12),
    sleep_hours: 7.5,
    rhr: 55,
    training_rpe: 0,
    pomodoros_completed: 8,
    tasks_completed: 6,
    macros_hit: true,
    hrv: 68,
    water_ml: 2800,
    mood: 4,
  },
  {
    date: daysAgo(11),
    sleep_hours: 8.0,
    rhr: 54,
    training_rpe: 8,
    pomodoros_completed: 6,
    tasks_completed: 5,
    macros_hit: true,
    hrv: 72,
    water_ml: 3000,
    mood: 5,
  },
  {
    date: daysAgo(10),
    sleep_hours: 7.0,
    rhr: 57,
    training_rpe: 6,
    pomodoros_completed: 5,
    tasks_completed: 4,
    macros_hit: true,
    hrv: 61,
    water_ml: 2500,
    mood: 4,
  },
  {
    date: daysAgo(9),
    sleep_hours: 6.0,
    rhr: 62,
    training_rpe: 0,
    pomodoros_completed: 3,
    tasks_completed: 2,
    macros_hit: false,
    hrv: 48,
    water_ml: 1800,
    mood: 2,
  },
  {
    date: daysAgo(8),
    sleep_hours: 9.0,
    rhr: 53,
    training_rpe: 7,
    pomodoros_completed: 7,
    tasks_completed: 6,
    macros_hit: true,
    hrv: 75,
    water_ml: 3200,
    mood: 5,
  },
  {
    date: daysAgo(7),
    sleep_hours: 7.5,
    rhr: 55,
    training_rpe: 9,
    pomodoros_completed: 4,
    tasks_completed: 3,
    macros_hit: true,
    hrv: 63,
    water_ml: 2600,
    mood: 4,
  },
  // Last 7 days (used in charts)
  {
    date: daysAgo(6),
    sleep_hours: 7.0,
    rhr: 56,
    training_rpe: 5,
    pomodoros_completed: 6,
    tasks_completed: 5,
    macros_hit: true,
    hrv: 66,
    water_ml: 2700,
    mood: 4,
  },
  {
    date: daysAgo(5),
    sleep_hours: 6.5,
    rhr: 59,
    training_rpe: 0,
    pomodoros_completed: 5,
    tasks_completed: 4,
    macros_hit: false,
    hrv: 58,
    water_ml: 2300,
    mood: 3,
  },
  {
    date: daysAgo(4),
    sleep_hours: 8.0,
    rhr: 54,
    training_rpe: 8,
    pomodoros_completed: 8,
    tasks_completed: 7,
    macros_hit: true,
    hrv: 74,
    water_ml: 3100,
    mood: 5,
  },
  {
    date: daysAgo(3),
    sleep_hours: 7.5,
    rhr: 55,
    training_rpe: 7,
    pomodoros_completed: 7,
    tasks_completed: 5,
    macros_hit: true,
    hrv: 70,
    water_ml: 2900,
    mood: 4,
  },
  {
    date: daysAgo(2),
    sleep_hours: 7.0,
    rhr: 57,
    training_rpe: 0,
    pomodoros_completed: 6,
    tasks_completed: 4,
    macros_hit: true,
    hrv: 65,
    water_ml: 2600,
    mood: 4,
  },
  {
    date: daysAgo(1),
    sleep_hours: 8.5,
    rhr: 52,
    training_rpe: 9,
    pomodoros_completed: 5,
    tasks_completed: 4,
    macros_hit: true,
    hrv: 71,
    water_ml: 3000,
    mood: 5,
  },
  {
    date: daysAgo(0),
    sleep_hours: 7.5,
    rhr: 55,
    training_rpe: 6,
    pomodoros_completed: 3,
    tasks_completed: 2,
    macros_hit: false,
    hrv: 60,
    water_ml: 1500,
    mood: 3,
  },
];

// ─── WORKOUT ENTRIES (last 4 weeks) ──────────────────────────
export const MOCK_WORKOUT_ENTRIES: WorkoutEntry[] = [
  // ── Bench Press ──
  {
    id: "w-001",
    date: daysAgo(21),
    exercise: "Bench Press",
    muscle_group: "Chest",
    weight: 80,
    weight_unit: "kg",
    reps: 8,
    sets: 4,
    progressive_overload_achieved: false,
  },
  {
    id: "w-002",
    date: daysAgo(14),
    exercise: "Bench Press",
    muscle_group: "Chest",
    weight: 82.5,
    weight_unit: "kg",
    reps: 8,
    sets: 4,
    progressive_overload_achieved: true,
  },
  {
    id: "w-003",
    date: daysAgo(7),
    exercise: "Bench Press",
    muscle_group: "Chest",
    weight: 82.5,
    weight_unit: "kg",
    reps: 9,
    sets: 4,
    progressive_overload_achieved: true,
  },
  {
    id: "w-004",
    date: daysAgo(0),
    exercise: "Bench Press",
    muscle_group: "Chest",
    weight: 85,
    weight_unit: "kg",
    reps: 8,
    sets: 4,
    progressive_overload_achieved: true,
  },

  // ── Squat ──
  {
    id: "w-005",
    date: daysAgo(20),
    exercise: "Back Squat",
    muscle_group: "Legs",
    weight: 100,
    weight_unit: "kg",
    reps: 6,
    sets: 5,
    progressive_overload_achieved: false,
  },
  {
    id: "w-006",
    date: daysAgo(13),
    exercise: "Back Squat",
    muscle_group: "Legs",
    weight: 102.5,
    weight_unit: "kg",
    reps: 6,
    sets: 5,
    progressive_overload_achieved: true,
  },
  {
    id: "w-007",
    date: daysAgo(6),
    exercise: "Back Squat",
    muscle_group: "Legs",
    weight: 105,
    weight_unit: "kg",
    reps: 6,
    sets: 5,
    progressive_overload_achieved: true,
  },

  // ── Deadlift ──
  {
    id: "w-008",
    date: daysAgo(19),
    exercise: "Romanian Deadlift",
    muscle_group: "Hamstrings",
    weight: 90,
    weight_unit: "kg",
    reps: 10,
    sets: 3,
    progressive_overload_achieved: false,
  },
  {
    id: "w-009",
    date: daysAgo(12),
    exercise: "Romanian Deadlift",
    muscle_group: "Hamstrings",
    weight: 92.5,
    weight_unit: "kg",
    reps: 10,
    sets: 3,
    progressive_overload_achieved: true,
  },
  {
    id: "w-010",
    date: daysAgo(5),
    exercise: "Romanian Deadlift",
    muscle_group: "Hamstrings",
    weight: 95,
    weight_unit: "kg",
    reps: 10,
    sets: 3,
    progressive_overload_achieved: true,
  },

  // ── Pull-up ──
  {
    id: "w-011",
    date: daysAgo(18),
    exercise: "Weighted Pull-up",
    muscle_group: "Back",
    weight: 10,
    weight_unit: "kg",
    reps: 8,
    sets: 4,
    progressive_overload_achieved: false,
  },
  {
    id: "w-012",
    date: daysAgo(11),
    exercise: "Weighted Pull-up",
    muscle_group: "Back",
    weight: 12.5,
    weight_unit: "kg",
    reps: 8,
    sets: 4,
    progressive_overload_achieved: true,
  },
  {
    id: "w-013",
    date: daysAgo(4),
    exercise: "Weighted Pull-up",
    muscle_group: "Back",
    weight: 12.5,
    weight_unit: "kg",
    reps: 9,
    sets: 4,
    progressive_overload_achieved: true,
  },

  // ── Overhead Press ──
  {
    id: "w-014",
    date: daysAgo(17),
    exercise: "Overhead Press",
    muscle_group: "Shoulders",
    weight: 60,
    weight_unit: "kg",
    reps: 6,
    sets: 4,
    progressive_overload_achieved: false,
  },
  {
    id: "w-015",
    date: daysAgo(10),
    exercise: "Overhead Press",
    muscle_group: "Shoulders",
    weight: 62.5,
    weight_unit: "kg",
    reps: 6,
    sets: 4,
    progressive_overload_achieved: true,
  },
  {
    id: "w-016",
    date: daysAgo(3),
    exercise: "Overhead Press",
    muscle_group: "Shoulders",
    weight: 62.5,
    weight_unit: "kg",
    reps: 7,
    sets: 4,
    progressive_overload_achieved: true,
  },
];

// ─── MACRO LOGS (last 7 days) ─────────────────────────────────
export const MOCK_MACRO_LOGS: MacroLog[] = [
  {
    date: daysAgo(6),
    calories_target: 2800,
    calories_actual: 2750,
    protein_g_target: 180,
    protein_g_actual: 175,
    carbs_g_target: 300,
    carbs_g_actual: 290,
    fat_g_target: 80,
    fat_g_actual: 78,
  },
  {
    date: daysAgo(5),
    calories_target: 2800,
    calories_actual: 2200,
    protein_g_target: 180,
    protein_g_actual: 140,
    carbs_g_target: 300,
    carbs_g_actual: 240,
    fat_g_target: 80,
    fat_g_actual: 60,
  },
  {
    date: daysAgo(4),
    calories_target: 2800,
    calories_actual: 2850,
    protein_g_target: 180,
    protein_g_actual: 185,
    carbs_g_target: 300,
    carbs_g_actual: 305,
    fat_g_target: 80,
    fat_g_actual: 82,
  },
  {
    date: daysAgo(3),
    calories_target: 2800,
    calories_actual: 2780,
    protein_g_target: 180,
    protein_g_actual: 178,
    carbs_g_target: 300,
    carbs_g_actual: 295,
    fat_g_target: 80,
    fat_g_actual: 79,
  },
  {
    date: daysAgo(2),
    calories_target: 2800,
    calories_actual: 2760,
    protein_g_target: 180,
    protein_g_actual: 172,
    carbs_g_target: 300,
    carbs_g_actual: 298,
    fat_g_target: 80,
    fat_g_actual: 77,
  },
  {
    date: daysAgo(1),
    calories_target: 2800,
    calories_actual: 2900,
    protein_g_target: 180,
    protein_g_actual: 190,
    carbs_g_target: 300,
    carbs_g_actual: 310,
    fat_g_target: 80,
    fat_g_actual: 85,
  },
  {
    date: daysAgo(0),
    calories_target: 2800,
    calories_actual: 1600,
    protein_g_target: 180,
    protein_g_actual: 95,
    carbs_g_target: 300,
    carbs_g_actual: 180,
    fat_g_target: 80,
    fat_g_actual: 55,
  },
];
